Ip 5451/add nat gateway
equinor/ioc-shared-infrastructure pull request #122
Opened 2024-05-30 13:18 UTC by tbequinor

2024-05-31 12:26 UTC, franktore requested changes

2024-05-31 12:26 UTC, franktore commented on resources/resourceVnet/azuredeploy.jsonc
> +    "name": "VirtualNetworkAssociation-20240514122833",
Why aren't we parametrizing this file? It is locked down to a specific resource in fiskal

2024-06-03 09:01 UTC, tbequinor commented on resources/resourceVnet/azuredeploy.jsonc
> +    "name": "VirtualNetworkAssociation-20240514122833",
Deleted this file. I think this file was provided to me after settings things up in the azure portal. Then I made bicep out of it and parameterised and tweaked that instead, and forgot about this. Voting to only keep the bicep version, so we don't have two places to make the same changes.

2024-06-04 08:11 UTC, franktore approved these changes
Good job!

2024-06-04 08:11 UTC, merged