Add outputs to resourceFunctionApp and resourceEventGrid
equinor/ioc-shared-infrastructure pull request #49
Opened 2020-10-07 15:35 UTC by inghel

Add outputs to resourceFunctionApp and resourceEventGrid

2020-10-07 18:56 UTC, lp-code requested changes

2020-10-07 18:56 UTC, lp-code commented on resources/resourceFunctionApp/azuredeploy.jsonc
> +    "objectId": {
Why are the values of objectId and identityObjectId exactly the opposite as for EventGrid? I assume at least ;-) one of them is wrong...

2020-10-08 06:40 UTC, jlyshoel commented on resources/resourceEventGrid/azuredeploy.jsonc
> +        }
Switch'd objectId and identityObjectId :-) Ref. comment from Lars, I'm pretty sure this is the wrong way around.

2020-10-08 19:42 UTC, jlyshoel approved these changes

2020-10-09 06:05 UTC, lp-code approved these changes

2020-10-09 06:15 UTC, merged